# This workflow will build a Karate project with Java

# This workflow is set to dispatch based on user input from a drop-down menu.
# Environment defaults to 'prod' and requires no selection. Test requires the choice of a tag before the run can begin.
# The fail-fast setting has been disabled to ensure that the entire test is allowed to complete in the presence of failures.
# This will allow actions to upload an Artifact for viewing regardless of results. Artifacts are labeled by test type and Date/Time

name: Karate

on:
  workflow_dispatch:
    inputs:
       env:
        description: 'Environment'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - dev
        - stg
        - secretDev
        - secretStg

       test:
        description: 'Test Type'             
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - regression


jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:     
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        
    - name: Run Karate with Java
      run: java -Dkey=${{secrets.API_KEY}}  -DsecretDev=${{secrets.CLD}} -DsecretStg=${{secrets.CLS}} -jar karate-1.4.1.jar -t @${{ inputs.test }} -e ${{ inputs.env }} test-directory -o test-directory/reports/

 
  result:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: build
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(TZ=":EST" date +'%Y-%m-%d %H.%MEST')" >>$GITHUB_OUTPUT
      
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1      
      if: ${{ always() }}
      with:
    # Artifact name
        name: ${{ inputs.test }} Result ${{ steps.date.outputs.date }}
    # A file, directory or wildcard pattern that describes what to upload
        path: test-directory/reports
        
  clean-up:
   runs-on: ubuntu-latest
   needs: result
   steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
